### ISSUE TITLE
Add support for alt attribute

### ISSUE THREAD

**Issue by Loupi** [danalloway/react-country-flag#24]
It would be nice to have a way to set the alt attribute of the img element that react-country-flag creates.

**Comment by danalloway** [comment]
@Loupi all props are forwarded to the element so just include a `alt` prop where you use this component and you're off to the races!

```JS
<ReactCountryFlag alt="United States" countryCode="US" />
```

**Comment by Loupi** [comment]
@danalloway Thank you! It works fine
