### ISSUE TITLE
Abkhazia flag is missing 

### ISSUE THREAD

**Issue by milix2019** [danalloway/react-country-flag#27]
first of all thanks for your lovely library. I am trying to add Abkhazia flag (AB) but seems like the flag doesn't exist. I am not sure the country code is wrong or this flag has been not implemented.

This is the url for the country:
 https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.3/flags/4x3/ab.svg

Thanks in advance.

**Comment by danalloway** [comment]
hey @milix2019 this library is just the React component that renders the flags, not the flag source itself
you may be looking to file an issue with this library (if there isn't one already)

https://github.com/lipis/flag-icon-css

cheers
