### ISSUE TITLE
Alt prop support

### ISSUE THREAD

**Issue by yanmendes** [danalloway/react-country-flag#28]
Hi there, thanks for maintaining this awesome lib! I've come across a use case that's not contemplated as of yet. I've been running my HTML code against [W3C's validator](https://validator.w3.org/) and I get the following error:

```
Error: An img element with no alt attribute must not have any aria-* attributes other than aria-hidden.

<img aria-label="Brazil" title="Brazil" src="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.3/flags/4x3/br.svg" style="display:inline-block;width:1em;height:1em;vertical-align:middle"/>
```

It would be great if you could provide an `alt` prop to your component and/or default an alt based on the country's code.

Cheers!

**Comment by danalloway** [comment]
hey @yanmendes

great idea, I'll consider defaulting the `alt` prop to the country code
in the meantime, all props are forwarded to the element already, if you include an `alt` prop it'll end up on your image tag and you'll pass validation.

cheers!
