### ISSUE TITLE
Flag CH showing Switzerland Flag

### ISSUE THREAD

**Issue by mayander30** [danalloway/react-country-flag#29]
I think that is wrong.

**Comment by DATeclipse** [comment]
> I think that is wrong.

Just had a look at the ISO Code for Switzerland, it seems correct here: https://en.wikipedia.org/wiki/ISO_3166-2:CH. Which flag were you looking for?

**Comment by mayander30** [comment]
i was looking for china, do you know is the flag ?

**Comment by DATeclipse** [comment]
> i was looking for china, do you know is the flag ?

This application is using Alpha-2 sets of ISO code so it would be CN. I've linked the list of ISO codes below for all countries for you as well if you want to have a look.

https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

If this solves your problem can you close the ticket.

**Comment by mayander30** [comment]
perfect, thank you.
