### ISSUE TITLE
Improve accessiblity

### ISSUE THREAD

**Issue by dawehner** [danalloway/react-country-flag#3]
Thank you for this component, exactly what I needed today :)

One small improvement which would be nice: Add some level of accessibility. Right now the output is purely the image itself. I think some form of title attribute on the span tag would already help.

What are you thoughts on that? I'm happy to submit a PR when we have reached an agreed path :)

**Comment by danalloway** [comment]
great idea, and I appreciate the offer for a PR but I'm about to cleanup a few things in there and don't mind adding this.

What do you think about a `title` tag, a `aria-label` and a `role` to cover our bases?
The `role` tag to indicate that the SVG is an image (dude to the fact that it's a backgroundImage with no content)
And the `title` tag and `aria-label` will indicate the value of the country code rendered.

Thoughts?

**Comment by dawehner** [comment]
> @dawehner great idea, and I appreciate the offer for a PR but I'm about to cleanup a few things in there and don't mind adding this.

Yeah one thing I learned over the years. Asking people before just doing a random PR has all kind of advantages :)

> What do you think about a title tag, a aria-label and a role to cover our bases?
The role tag to indicate that the SVG is an image (dude to the fact that it's a backgroundImage with no content)
And the title tag and aria-label will indicate the value of the country code rendered.

This sounds excellent. 👍

**Comment by danalloway** [comment]
ebf26803c4a984750efff0e5da0ad2226734a7d3

**Comment by dawehner** [comment]
Yeah, thank you @danalloway !
