### ISSUE TITLE
Flag missed to Netherlands Antilles

### ISSUE THREAD

**Issue by crar01** [danalloway/react-country-flag#30]
Flag missed to countryCode = 'AN' :
https://www.iso.org/obp/ui/#iso:code:3166:AN

**Comment by danalloway** [comment]
this library not a source for flags, it uses the flags from https://github.com/lipis/flag-icon-css
if a flag you need is missing you can open an issue at the repo linked above, or swap out the SVG flag library entirely by passing in the `cdnUrl` prop and pointing to an alternative one that suits your needs

**Comment by andyford** [comment]
for anyone else landing here because they thought that `AN` was excluded from the data by mistake, please note that the country was dissolved in 2010 https://en.wikipedia.org/wiki/Netherlands_Antilles
