### ISSUE TITLE
Please use white-red-white version of belarusian flag

### ISSUE THREAD

**Issue by AllDayAlone** [danalloway/react-country-flag#33]
The red-green flag is associated with president Lukashenko who is called "Europe's last dictator". Please, use our national flag to support the people of Belarus.

https://www.euronews.com/2020/08/26/telegram-changes-emoji-of-belarus-flag-in-solidarity-with-protesters-thecube
![image](https://user-images.githubusercontent.com/32430949/93200514-847a1f00-f758-11ea-8dc8-219d8ccc068d.png)
![image](https://user-images.githubusercontent.com/32430949/93200529-8a700000-f758-11ea-8eff-ca36fbd23c9f.png)

**Comment by danalloway** [comment]
Hi, this library doesn't have any flags included in it, it references this flag library https://github.com/lipis/flag-icon-css via a CDN URL which you may change to whatever flag provider you'd like
