### ISSUE TITLE
Retrieve all SVGs on a single fetch

### ISSUE THREAD

**Issue by neosepulveda** [danalloway/react-country-flag#35]
Hi there,

I am currently working on a country selector, I am using `react-country-flag` to display a little flag next to the country name. Unfortunately, the loading time is quite high due to all the fetch requests (one per flag)
Is there any way to avoid this? Perhaps download everything on a single fetch?

![image](https://user-images.githubusercontent.com/8416547/93478322-abb92380-f8f3-11ea-860b-5c418800d516.png)

**Comment by danalloway** [comment]
good question, but based on the flag icon library we're using and the way this component was written I'm not sure how that would be possible

**Comment by danalloway** [comment]
you would need to explore loading all the flags as a sprite and then designing a component to render them properly that way

**Comment by danalloway** [comment]
caveat, it would be a HUGE image file
