### ISSUE TITLE
react-country-flag – UK flag is missed on CDN

### ISSUE THREAD

**Issue by antonioMerkulov** [danalloway/react-country-flag#36]
Could you please add UK flag? https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.3/flags/4x3/uk.svg

**Comment by zoloautor** [comment]
If you mean United Kingdom - it's GB, if Ukraine, it's UA

**Comment by danalloway** [comment]
the SVG flags from from another library, this is just the React component that renders them
see https://github.com/lipis/flag-icons for the flag library

@zoloautor is correct it's GB that you're looking for, see here

https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/4.1.4/flags/4x3/gb.svg
