### ISSUE TITLE
Emoji's are not supported in Chromium based browsers 

### ISSUE THREAD

**Issue by akshaycj** [danalloway/react-country-flag#38]
![image](https://user-images.githubusercontent.com/14146831/109632248-d24edc00-7b6c-11eb-81ef-915efe0ce7c1.png)

Works fine in Firefox, but not on the ones below:
Google chrome
Edge
Brave

**Comment by danalloway** [comment]
I suggest you check for this particular browser in your code than render an alternative
this library does not do browser checking
