### ISSUE TITLE
Update to work with React 17

### ISSUE THREAD

**Issue by acolle** [danalloway/react-country-flag#39]
Would it be possible to update the project to work with React 17?
It's currently only accepting version 15 or 16.
Thanks

**Comment by skipjack** [comment]
Ran into this as well. You can get past the `npm` v7 error like so...

``` bash 
npm i --legacy-peer-deps react-country-flag
```

Package appears to be working fine as far as I can tell, not seeing any glaring [breaking changes][1] that would have an effect here. Still would be nice to bump the `peerDependencies` here though.

[1]: https://github.com/facebook/react/releases/tag/v17.0.0

**Comment by TomlDev** [comment]
Yea would be cool to get this!

**Comment by dylan-13** [comment]
Yeah please update it to work with V17 of React 🛐

**Comment by dylan-13** [comment]
Following the release of version 2.3.1 you can close this issu, @danalloway  🛐

**Comment by danalloway** [comment]
thanks @dylan-13 ! closing after this commit ed369627e8e050ec14fd194a9c9073495f8e4263
