### ISSUE TITLE
Component triggers HTML5 Canvas fingerprinting protections

### ISSUE THREAD

**Issue by shakhbulatgaz** [danalloway/react-country-flag#4]
When i render this component, browser asks my permission to let server read the HTML5 canvas data.
Why is that? Besides, no functionality suffers if i don't allow that.

**Comment by danalloway** [comment]
the emoji check most likely triggers that

what browser / version are you getting that in?

**Comment by danalloway** [comment]
honestly, the emoji check is mostly bloat and can be removed
published a new version without it

**Comment by shakhbulatgaz** [comment]
Answering your question, the browser is Firefox 61.0.2.
This happens only in Firefox, thought, Chrome and Opera don't care.

I'll check the new version today, thank you.

**Comment by danalloway** [comment]
the new version also contains a considerable tooling change on how I build the project, the demo page tested out ok but let me know if you experience any issues on your end

**Comment by danalloway** [comment]
@shakhbulatgaz any luck?

**Comment by shakhbulatgaz** [comment]
@danalloway oh shoot, sorry. Yes, it works beautifully. No protections triggered, no functionality suffered.
