### ISSUE TITLE
Swiss (SVG) flag has wrong aspect ratio

### ISSUE THREAD

**Issue by N3XT191** [danalloway/react-country-flag#43]
The flag of Switzerland displays a white cross in the centre of a square red field. The white cross is known as the Swiss cross. Its arms are equilateral, and their ratio of length to width is 7:6. The size of the cross in relation to the field was set in 2017 as 5:8.

https://en.m.wikipedia.org/wiki/Flag_of_Switzerland

the SVG for the Swiss flag in this package is wrong (3:2 probably?) but it should be square (1:1)

**Comment by N3XT191** [comment]
To clarify, there exists a 3:2 flag, but that is only used on boats, ships and some other minor places. The flag flown by the Gouvernement and all the people who know what they are doing is square

**Comment by danalloway** [comment]
the flags come from another library, this library is just the React component that renders them
see here for the actual flag library https://github.com/lipis/flag-icons

if you would like to use the square versions of all flags, pass in the `cdnUrl` override

```
<ReactCountryFlag countryCode="CH" cdnUrl="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/4.1.4/flags/1x1/" />
```
