### ISSUE TITLE
Tristan da Cunha (TA) and Ascension SVGs are missing 

### ISSUE THREAD

**Issue by mo-othman** [danalloway/react-country-flag#44]
Tristan da Cunha (country cody => ), Ascension (country code => AC)

are available as icons but not SVG

**Comment by danalloway** [comment]
this library does not have the actual SVGs in it, the SVG flag library lives here:
https://github.com/lipis/flag-icons
open an issue there for missing flags

this library just loads whatever is available over there, depending on the country code
