### ISSUE TITLE
Close Completed Issues!!

### ISSUE THREAD

**Issue by jrbgit** [danalloway/react-country-flag#45]
One of the first things I do when looking for a package is check the issues to see what open issues there are and if reported issues have been resolved. There are several issues that were answered or fixed but they are still open! Please close them - it makes the project look better maintained...

**Comment by jrbgit** [comment]
Examples:
 #38 -- This is a browser issue, not an issue with the package
 #36 -- Answered Correctly
 #35 -- Feature Request - not an issue
 #34 -- Done ( #16 ) but not closed...

**Comment by danalloway** [comment]
on it!
