### ISSUE TITLE
How can I add custom png files to this library?

### ISSUE THREAD

**Issue by vincentsartoko** [danalloway/react-country-flag#46]
I want to add some game flags (e.g. Dota 2), and maybe it can check the countryCode property, if it is "dota2", it can fetch a custom image from a folder instead of from Cloudflare website. I have tried putting the code and change the "src" on index.js file like so:

```
var dota2Image = require("../custom/dota2.png");
if (svg) {
    var flagUrl = "".concat(cdnUrl).concat(countryCode.toLowerCase(), ".").concat(DEFAULT_CDN_SUFFIX);
    if (countryCode === "dota2") flagUrl = dota2Image;
    return /*#__PURE__*/React__namespace.createElement("img", _extends({}, props, {
      src: flagUrl,
      style: _objectSpread({
        display: 'inline-block',
        width: '1em',
        height: '1em',
        verticalAlign: 'middle'
      }, style)
    }));
  }
```

However, the result is not what I expected, it just shows the "title" props. If you know how to solve my problem please let me know :)

**Comment by danalloway** [comment]
this library is designed around loading flags from a single CDN origin
if you want to do something different based on the `dota2` countryCode handle that in your own code before you render this component, like this

```
import ReactCountryFlag from "react-country-flag";
import { YourDotaImageComponent } from "./YourDotaImageComponent";

export function YourComponent(countryCode) {
    if (countryCode === "dota2") {
        return <YourDotaImageComponent />
    }

    return <ReactCountryFlag svg countryCode={countryCode} />
}
```

you can load from wherever you want and render whatever you want in your own image component, then it uses this component for everything else
