### ISSUE TITLE
bumping version to react-country-flag 3.00 causes error

### ISSUE THREAD

**Issue by CourtHive** [danalloway/react-country-flag#48]
Dan,

```js
git clone git@github.com:CourtHive/tods-score-grid.git

yarn install
yarn storybook
```

All is well

Edit `package.json` and bump the version of `react-country-flag`

```js
yarn install 
yarn storybook
```

"Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports."

_Originally posted by @CourtHive in https://github.com/danalloway/react-country-flag/issues/47#issuecomment-974763054_

**Comment by danalloway** [comment]
fixed in v3.0.2 where added a default export back in
