### ISSUE TITLE
Complete types from each keys

### ISSUE THREAD

**Issue by amerllica** [danalloway/react-country-flag#49]
Thanks for your awesome library, it would be better to export types for each key in `Country` object. for example `iso`, it is not string, it is `ISO3166Alpha2`. I will send a PR for this improvement.

**Comment by danalloway** [comment]
while this is technically correct, this library doesn't maintain a list of country codes
and changing the type means that it would have to

if strictness and enforcement of valid country codes is a concern to you, then export them into your project and do the enforcement there

this library is just an React / HTML wrapper around an element and nothing more, I don't want to get into the Country Could / Flag business with it

**Comment by amerllica** [comment]
Wow, what a cruel answer, I just want to help this library to make it better.

**Comment by danalloway** [comment]
@amerllica apologies if that came across as cruel to you, that was not my intention at all whatsoever. I actually took the time to answer you well and as detailed as I could about why I don’t think it’s a good idea. I meant to harshness by it, apologies again for that misunderstanding.

I super  appreciate your desire to help and make this live set better though, thank you!
