### ISSUE TITLE
Country flags missing for Kosovo (XK) and Netherland Antilles (AN)

### ISSUE THREAD

**Issue by joshlbaker** [danalloway/react-country-flag#5]
- Flags show up blank for these two countries
- I believe `Netherland Antilles` is just `The Netherlands` so I can always just map one to the other, just wanted to bring it to your attention.
- Using latest `v1.0.1`

**Comment by danalloway** [comment]
ACK.
I'll take look into this as soon as I'm able.
Thanks for reporting this.

**Comment by joshlbaker** [comment]
Amazing, thank you!

**Comment by danalloway** [comment]
haven't forgotten about this, will have something in during the holiday break most likely

**Comment by joshlbaker** [comment]
@danalloway the CDN you were using to import the flag svgs has been updated with these flags so all you should need to do is update that to the latest `3.2.1`

**Comment by danalloway** [comment]
using latest CDN v3.2.1 as of our release 1.0.2

**Comment by LCCalado** [comment]
I am using the latest version (1.0.2) and I am still getting 404 on 3 flags:
`GET https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.1/flags/4x3/kv.svg 404
an.svg:1
GET https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.1/flags/4x3/an.svg 404
ic.svg:1 
GET https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.1/flags/4x3/ic.svg 404`

**Comment by danalloway** [comment]
@LCCalado yea that is correct, can't do much about that
also, the ISO country code for Kosovo is `XK` not KV give that a try https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/xk.svg

**Comment by LCCalado** [comment]
Thanks. What about "Netherland Antilles" and "Canary Islands"?

**Comment by danalloway** [comment]
I don't maintain the Flag library so I'm not sure why they are not included, there are no emoticons for them either.
I would recommend a custom solution for those edge case flags.

**Comment by vincentsartoko** [comment]
> I don't maintain the Flag library so I'm not sure why they are not included, there are no emoticons for them either. I would recommend a custom solution for those edge case flags.

@danalloway Can you guide me on how to put custom flags? Thank you :)
