### ISSUE TITLE
Missing two country flags

### ISSUE THREAD

**Issue by Lucas-Calzolari** [danalloway/react-country-flag#52]
There are no flag for codes:
TA Tristan da Cunha 
AC Ascension

It would be nice to have those to avoid manually handling those cases when getting list of countries from other libs.

**Comment by danalloway** [comment]
Emoji versions or SVG flags?

**Comment by danalloway** [comment]
@Lucas-Calzolari if you want the Emoji versions, that is part of the Unicode spec and we can only use what they release
for SVG's we use this SVG library CDN https://flagicons.lipis.dev

so any flags you need there can be opened via GitHub issue
hope that helps!
