### ISSUE TITLE
Handle a 404 error

### ISSUE THREAD

**Issue by mccm2310** [danalloway/react-country-flag#59]
There is no way to handle a query error if the countryCode doesn't exist in cdnjs flags. For example, 'GZ' or 'AN'.

**Comment by kodsu** [comment]
Yes there is -> onError event.

```jsx
<ReactCountryFlag
	className="h-4 w-4"
	countryCode={movie.lang.toLowerCase()}
	svg
	onError={() => console.log('error')} />
```

**Comment by danalloway** [comment]
@keytrap-x86 thank you for that example!

@mccm2310 this library is just a wrapper around an <img> for SVG flags, and a <span> for emoji's, all props pass through so the comment above is a perfect example of that
