### ISSUE TITLE
Stars element on US flag misplaced

### ISSUE THREAD

**Issue by eirikhanasand** [danalloway/react-country-flag#61]
The star element on the US flag is misplaced. This causes a big issue in React Native, where the stars will be misplaced in the top left corner, with one row half way outside the flag.

Browser inspection:
<img width="1511" alt="us" src="https://github.com/danalloway/react-country-flag/assets/59398022/7c157551-1e58-4f4a-954d-72a145578779">
As you can see the star element is off by a tad bit. This looks fine in the browser, but when trying to use it in React Native it breaks. (I know this is a react library, but it is still a bug that just so happens to look fine in the browser, and there will be no negative consequences in fixing it)

React native result:
<img width="1511" alt="us2" src="https://cdn.discordapp.com/attachments/244238416248569857/1117797536858652682/IMG_2088.png">

Properly placing the star element should fix things in React Native, and fix an unnoticed bug.

**Comment by danalloway** [comment]
@eirikhanasand thanks for your feedback!

the flag SVGs come from this library https://github.com/lipis/flag-icons, I'd suggest bringing up this issue over there
