### ISSUE TITLE
Missing flag

### ISSUE THREAD

**Issue by MortezaHeydari97** [danalloway/react-country-flag#66]
Hi,
There is no flag provided for `Netherlands Antilles` country.

**Comment by meet-bhalodiya-ocl** [comment]
Yup that flag needs to be added

**Comment by danalloway** [comment]
Hi, this library doesn't have any flags included in it, it references this flag library https://github.com/lipis/flag-icon-css via a cdnUrl prop which you may change to whatever flag provider you'd like. As for emoji flags, they are all part of the emoji unicode spec that can be found here https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
