### ISSUE TITLE
Is it possible to add countries that are not available?

### ISSUE THREAD

**Issue by victorgonzalezz** [danalloway/react-country-flag#67]
For example, there is no flag of Zanzibar and i need it :)

**Comment by danalloway** [comment]
Hi, this library doesn't have any flags included in it, it references this flag library https://github.com/lipis/flag-icon-css via a cdnUrl prop which you may change to whatever flag provider you'd like. As for emoji flags, they are all part of the emoji unicode spec that can be found here https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
