### ISSUE TITLE
Installing through Yarn

### ISSUE THREAD

**Issue by rash2x** [danalloway/react-country-flag#7]
Hi there! 

When I try to install the package through yarn I have next errors: 

`yarn add react-country-flag`

```
yarn add v1.6.0
[1/4] 🔍  Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/react-country-flag: getaddrinfo ENOTFOUND registry.yarnpkg.com registry.yarnpkg.com:443".
info If you think this is a bug, please open a bug report with the information provided in "/Users/rash2x/WebstormProjects/Calendars/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by frasergr** [comment]
"info There appears to be trouble with your network connection. Retrying..." indicates an issue with your network or system. I was able to add via yarn a few minutes ago without issue.

**Comment by rash2x** [comment]
when I try to install the package through npm, everything works well.

**Comment by blatinier** [comment]
For what's worth I don't have the issue with yarn:

    $ yarn add react-country-flag
    yarn add v1.5.1
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    info fsevents@1.2.4: The platform "linux" is incompatible with this module.
    info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from     installation.
    [3/4] Linking dependencies...
    warning "antd > rc-editor-mention@1.1.7" has unmet peer dependency "immutable@^3.7.4".
    [4/4] Building fresh packages...
    success Saved lockfile.
    success Saved 1 new dependency.
    info Direct dependencies
    └─ react-country-flag@1.0.1
    info All dependencies
    └─ react-country-flag@1.0.1
    Done in 5.71s.

Using yarn 1.5.1 (yeah not really up to date…)

**Comment by danalloway** [comment]
@rash2x have you tried it agin using `yarn` any change?

**Comment by rash2x** [comment]
Thanks guys. Looks like you are right. I close the issue.
