### ISSUE TITLE
Windows 10 flag emoji suppport

### ISSUE THREAD

**Issue by sersart** [danalloway/react-country-flag#8]
Hi, I have problem with Edge browser, icon does not showing.
Thanks

**Comment by danalloway** [comment]
ACK.
I'll take a look as soon as I'm able.
Thanks

**Comment by mooncitizen** [comment]
just to hijack here IE11 is the same!

**Comment by zainimran** [comment]
It's the same across Chrome/FF/Edge on Windows 10. That's cause windows 10 doesn't support flag emojis at the moment. Can we have a fallback option where svg flag would render where emoji isn't available?

**Comment by danalloway** [comment]
Please use https://github.com/danalloway/detect-emoji-support to conditionally render your `ReactCountryFlag` component.

Please note that this will cause browsers like Firefox to trigger a canvas warning. Which is why I'm not including it by default in this library.

**Comment by danalloway** [comment]
wanted to revisit this as the solution I posted above will not work properly on Windows 10 as it supports emoji's but will not interrupt flag emoji's

as of right now Windows 10 does not support interpreting flag emojis, so you'll need to OS detect and fallback to SVG in the meantime
